-- Create schema for ODS
CREATE SCHEMA IF NOT EXISTS UDACITYDWHPROJECT.ODS;

-- create Business table
CREATE OR REPLACE TABLE UDACITYDWHPROJECT.ODS.BUSINESS (
    BUSINESS_SK NUMBER IDENTITY(1,1), -- Surrogate Key
    BUSINESS_ID VARCHAR(16777216),    -- Natural Key
    NAME VARCHAR(16777216),
    ADDRESS VARCHAR(16777216),
    CITY VARCHAR(16777216),
    STATE VARCHAR(16777216),
    POSTAL_CODE VARCHAR(16777216),
    LATITUDE NUMBER(38,10),
    LONGITUDE NUMBER(38,10),
    STARS NUMBER(38,1),
    REVIEW_COUNT NUMBER(38,0),
    IS_OPEN NUMBER(38,0),
    CATEGORIES VARCHAR(16777216),
    VALID_FROM TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    VALID_TO TIMESTAMP_NTZ DEFAULT NULL,
    IS_CURRENT BOOLEAN DEFAULT TRUE
);

-- Update BUSINESS table
ALTER TABLE UDACITYDWHPROJECT.ODS.BUSINESS
ADD CONSTRAINT PK_DIM_BUSINESS PRIMARY KEY (BUSINESS_SK);

-- create Customer table
CREATE OR REPLACE TABLE UDACITYDWHPROJECT.ODS.CUSTOMER (
    CUSTOMER_SK NUMBER IDENTITY(1,1),  -- Surrogate Key
    USER_ID VARCHAR(16777216),         -- Natural Key
    NAME VARCHAR(16777216),
    REVIEW_COUNT NUMBER(38,0),
    YELPING_SINCE TIMESTAMP_NTZ(9),
    AVERAGE_STARS NUMBER(38,2),
    FANS NUMBER(38,0),
    ELITE VARCHAR(16777216),
    VALID_FROM TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    VALID_TO TIMESTAMP_NTZ DEFAULT NULL,
    IS_CURRENT BOOLEAN DEFAULT TRUE
);

-- Update CUSTOMER table  
ALTER TABLE UDACITYDWHPROJECT.ODS.CUSTOMER
ADD CONSTRAINT PK_DIM_CUSTOMER PRIMARY KEY (CUSTOMER_SK);

-- create Date table
CREATE OR REPLACE TABLE UDACITYDWHPROJECT.ODS.DATE (
    DATE_SK NUMBER(38,0),             -- Surrogate Key (YYYYMMDD format)
    FULL_DATE DATE,
    YEAR NUMBER(4,0),
    MONTH NUMBER(2,0),
    DAY NUMBER(2,0),
    QUARTER NUMBER(1,0),
    DAY_OF_WEEK NUMBER(1,0),
    WEEK_OF_YEAR NUMBER(2,0)
);

-- Update DATE table
ALTER TABLE UDACITYDWHPROJECT.ODS.DATE
ADD CONSTRAINT PK_DIM_DATE PRIMARY KEY (DATE_SK);

-- create Review table
CREATE OR REPLACE TABLE UDACITYDWHPROJECT.ODS.REVIEW (
    REVIEW_ID VARCHAR(16777216),      -- Natural Key
    BUSINESS_SK NUMBER,               -- Foreign Key to BUSINESS
    CUSTOMER_SK NUMBER,               -- Foreign Key to CUSTOMER
    DATE_SK NUMBER(38,0),             -- Foreign Key to DATE
    STARS NUMBER(38,1),
    USEFUL NUMBER(38,0),
    FUNNY NUMBER(38,0),
    COOL NUMBER(38,0),
    TEXT VARCHAR(16777216),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT FK_FACT_REVIEW_BUSINESS FOREIGN KEY (BUSINESS_SK) REFERENCES 
    UDACITYDWHPROJECT.ODS.BUSINESS(BUSINESS_SK),
    CONSTRAINT FK_FACT_REVIEW_CUSTOMER FOREIGN KEY (CUSTOMER_SK) REFERENCES 
    UDACITYDWHPROJECT.ODS.CUSTOMER(CUSTOMER_SK),
    CONSTRAINT FK_FACT_REVIEW_DATE FOREIGN KEY (DATE_SK) REFERENCES UDACITYDWHPROJECT.ODS.DATE(DATE_SK)
);

-- create Check-in table 
CREATE OR REPLACE TABLE UDACITYDWHPROJECT.ODS.CHECKIN (
    CHECKIN_SK NUMBER IDENTITY(1,1),  -- Surrogate Key
    BUSINESS_SK NUMBER,               -- Foreign Key to DIM_BUSINESS
    DATE_SK NUMBER(38,0),             -- Foreign Key to DIM_DATE
    CHECKIN_COUNT NUMBER(38,0),       -- Aggregated count of check-ins per business per date
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    FOREIGN KEY (BUSINESS_SK) REFERENCES UDACITYDWHPROJECT.ODS.BUSINESS(BUSINESS_SK),
    FOREIGN KEY (DATE_SK) REFERENCES UDACITYDWHPROJECT.ODS.DATE(DATE_SK)
);

-- create Weather table
CREATE OR REPLACE TABLE UDACITYDWHPROJECT.ODS.WEATHER (
    WEATHER_SK NUMBER IDENTITY(1,1),  -- Surrogate Key
    DATE_SK NUMBER(38,0),             -- Foreign Key to DIM_DATE
    PRECIPITATION NUMBER(38,2),
    PRECIPITATION_NORMAL NUMBER(38,2),
    TEMPERATURE_MIN NUMBER(38,1),
    TEMPERATURE_MAX NUMBER(38,1),
    TEMPERATURE_NORMAL_MIN NUMBER(38,1),
    TEMPERATURE_NORMAL_MAX NUMBER(38,1),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    FOREIGN KEY (DATE_SK) REFERENCES UDACITYDWHPROJECT.ODS.DATE(DATE_SK)
);

-- create Covid table
CREATE OR REPLACE TABLE UDACITYDWHPROJECT.ODS.COVID (
    COVID_SK NUMBER IDENTITY(1,1),    -- Surrogate Key
    BUSINESS_SK NUMBER,               -- Foreign Key to DIM_BUSINESS
    DELIVERY_OR_TAKEOUT VARCHAR(16777216),
    VIRTUAL_SERVICES_OFFERED VARCHAR(16777216),
    TEMPORARY_CLOSED_UNTIL VARCHAR(16777216),
    VALID_FROM TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    VALID_TO TIMESTAMP_NTZ DEFAULT NULL,
    IS_CURRENT BOOLEAN DEFAULT TRUE,
    FOREIGN KEY (BUSINESS_SK) REFERENCES UDACITYDWHPROJECT.ODS.BUSINESS(BUSINESS_SK)
);

-- create the TIPS table
CREATE OR REPLACE TABLE UDACITYDWHPROJECT.ODS.TIPS (
    TIP_SK NUMBER(38,0) AUTOINCREMENT START 1 INCREMENT 1 NOORDER,
    BUSINESS_SK NUMBER(38,0),
    CUSTOMER_SK NUMBER(38,0),
    DATE_SK NUMBER(38,0),
    COMPLIMENT_COUNT NUMBER(38,0),
    TIP_TEXT VARCHAR(16777216),
    CONSTRAINT PK_TIPS PRIMARY KEY (TIP_SK),
    CONSTRAINT FK_TIPS_BUSINESS FOREIGN KEY (BUSINESS_SK) REFERENCES UDACITYDWHPROJECT.ODS.BUSINESS(BUSINESS_SK),
    CONSTRAINT FK_TIPS_CUSTOMER FOREIGN KEY (CUSTOMER_SK) REFERENCES UDACITYDWHPROJECT.ODS.CUSTOMER(CUSTOMER_SK),
    CONSTRAINT FK_TIPS_DATE FOREIGN KEY (DATE_SK) REFERENCES UDACITYDWHPROJECT.ODS.DATE(DATE_SK)
);

